### ISSUE TITLE
Dockerize ElasticSearch

### ISSUE THREAD

**Issue by congwang09** [atlanticwave-sdx/sdx-controller#113] opened 2022-12-15 14:56 UTC
The current prototype's ElasticSearch uses a one time script to install, and run in host machine. We should use Docker ElasticSearch instead.

**Comment by sajith** [comment] 2024-06-08 00:46
Done in https://github.com/atlanticwave-sdx/sdx-controller/pull/201.  Also duplicate of https://github.com/atlanticwave-sdx/sdx-controller/issues/167.

**Closed by sajith** 2024-06-08 00:46 UTC
Labels: enhancement, epic_ci/cd
